---
abstract: 'use Matrix with L<IO::Async>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-Matrix
provides:
  Net::Async::Matrix:
    file: lib/Net/Async/Matrix.pm
    version: '0.04'
  Net::Async::Matrix::Room:
    file: lib/Net/Async/Matrix/Room.pm
    version: '0.04'
requires:
  Data::Dump: '0'
  Future::Utils: '0'
  IO::Async::Notifier: '0'
  JSON: '0'
  Net::Async::HTTP: '0'
  POSIX: '0'
  Struct::Dumb: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.04'
